# Generated by Django 2.1 on 2019-12-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0011_globalconfig_last_automated_service_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='pos_supervisor_password',
            field=models.CharField(default='1234', max_length=16),
        ),
    ]
