# Generated by Django 2.1 on 2020-01-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0012_globalconfig_pos_supervisor_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalconfig',
            name='last_license_check',
        ),
        migrations.RemoveField(
            model_name='globalconfig',
            name='verification_task_id',
        ),
    ]
