# Generated by Django 2.1 on 2020-02-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0013_auto_20200102_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconfig',
            name='application_version',
            field=models.CharField(blank=True, default='1.0.0', max_length=16),
        ),
    ]
