# Generated by Django 2.2.13 on 2020-09-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0016_note_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='supports_quick_entry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='supports_quick_entry',
            field=models.BooleanField(default=True),
        ),
    ]
