# Generated by Django 2.1 on 2020-02-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_auto_20191126_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollofficer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
