# Generated by Django 2.1 on 2020-02-20 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_payrollofficer_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollofficer',
            name='employee',
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
    ]
