# Generated by Django 2.2.10 on 2020-03-23 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0026_shift_shiftschedule_shiftscheduleline'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftschedule',
            name='valid_from',
            field=models.DateField(default=datetime.date(2020, 3, 23)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='valid_to',
            field=models.DateField(default=datetime.date(2020, 3, 23)),
            preserve_default=False,
        ),
    ]
