# Generated by Django 2.2.13 on 2020-09-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0027_auto_20200323_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='supports_quick_entry',
            field=models.BooleanField(default=True),
        ),
    ]
