# Generated by Django 2.1 on 2020-01-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20190923_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceperson',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
