# Generated by Django 2.2.10 on 2020-03-15 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20200302_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceworkorder',
            name='expected_duration',
            field=models.DurationField(blank=True, choices=[(datetime.timedelta(0), '00:00'), (datetime.timedelta(0, 1800), '00:30'), (datetime.timedelta(0, 3600), '01:00'), (datetime.timedelta(0, 5400), '01:30'), (datetime.timedelta(0, 7200), '02:00'), (datetime.timedelta(0, 9000), '02:30'), (datetime.timedelta(0, 10800), '03:00'), (datetime.timedelta(0, 12600), '03:30'), (datetime.timedelta(0, 14400), '04:00'), (datetime.timedelta(0, 16200), '04:30'), (datetime.timedelta(0, 18000), '05:00'), (datetime.timedelta(0, 19800), '05:30'), (datetime.timedelta(0, 21600), '06:00'), (datetime.timedelta(0, 23400), '06:30'), (datetime.timedelta(0, 25200), '07:00'), (datetime.timedelta(0, 27000), '07:30'), (datetime.timedelta(0, 28800), '08:00'), (datetime.timedelta(0, 30600), '08:30'), (datetime.timedelta(0, 32400), '09:00'), (datetime.timedelta(0, 34200), '09:30'), (datetime.timedelta(0, 36000), '10:00'), (datetime.timedelta(0, 37800), '10:30'), (datetime.timedelta(0, 39600), '11:00'), (datetime.timedelta(0, 41400), '11:30'), (datetime.timedelta(0, 43200), '12:00'), (datetime.timedelta(0, 45000), '12:30'), (datetime.timedelta(0, 46800), '13:00'), (datetime.timedelta(0, 48600), '13:30'), (datetime.timedelta(0, 50400), '14:00'), (datetime.timedelta(0, 52200), '14:30'), (datetime.timedelta(0, 54000), '15:00'), (datetime.timedelta(0, 55800), '15:30'), (datetime.timedelta(0, 57600), '16:00'), (datetime.timedelta(0, 59400), '16:30'), (datetime.timedelta(0, 61200), '17:00'), (datetime.timedelta(0, 63000), '17:30'), (datetime.timedelta(0, 64800), '18:00'), (datetime.timedelta(0, 66600), '18:30'), (datetime.timedelta(0, 68400), '19:00'), (datetime.timedelta(0, 70200), '19:30'), (datetime.timedelta(0, 72000), '20:00'), (datetime.timedelta(0, 73800), '20:30'), (datetime.timedelta(0, 75600), '21:00'), (datetime.timedelta(0, 77400), '21:30'), (datetime.timedelta(0, 79200), '22:00'), (datetime.timedelta(0, 81000), '22:30'), (datetime.timedelta(0, 82800), '23:00')], null=True),
        ),
        migrations.AlterField(
            model_name='serviceworkorder',
            name='time',
            field=models.TimeField(choices=[(datetime.time(0, 0), '00:00'), (datetime.time(0, 30), '00:30'), (datetime.time(1, 0), '01:00'), (datetime.time(1, 30), '01:30'), (datetime.time(2, 0), '02:00'), (datetime.time(2, 30), '02:30'), (datetime.time(3, 0), '03:00'), (datetime.time(3, 30), '03:30'), (datetime.time(4, 0), '04:00'), (datetime.time(4, 30), '04:30'), (datetime.time(5, 0), '05:00'), (datetime.time(5, 30), '05:30'), (datetime.time(6, 0), '06:00'), (datetime.time(6, 30), '06:30'), (datetime.time(7, 0), '07:00'), (datetime.time(7, 30), '07:30'), (datetime.time(8, 0), '08:00'), (datetime.time(8, 30), '08:30'), (datetime.time(9, 0), '09:00'), (datetime.time(9, 30), '09:30'), (datetime.time(10, 0), '10:00'), (datetime.time(10, 30), '10:30'), (datetime.time(11, 0), '11:00'), (datetime.time(11, 30), '11:30'), (datetime.time(12, 0), '12:00'), (datetime.time(12, 30), '12:30'), (datetime.time(13, 0), '13:00'), (datetime.time(13, 30), '13:30'), (datetime.time(14, 0), '14:00'), (datetime.time(14, 30), '14:30'), (datetime.time(15, 0), '15:00'), (datetime.time(15, 30), '15:30'), (datetime.time(16, 0), '16:00'), (datetime.time(16, 30), '16:30'), (datetime.time(17, 0), '17:00'), (datetime.time(17, 30), '17:30'), (datetime.time(18, 0), '18:00'), (datetime.time(18, 30), '18:30'), (datetime.time(19, 0), '19:00'), (datetime.time(19, 30), '19:30'), (datetime.time(20, 0), '20:00'), (datetime.time(20, 30), '20:30'), (datetime.time(21, 0), '21:00'), (datetime.time(21, 30), '21:30'), (datetime.time(22, 0), '22:00'), (datetime.time(22, 30), '22:30'), (datetime.time(23, 0), '23:00')]),
        ),
    ]
