# Generated by Django 2.2.10 on 2020-03-25 10:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20200315_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordertask',
            name='dependency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.WorkOrderTask'),
        ),
        migrations.AddField(
            model_name='workordertask',
            name='start',
            field=models.DateField(blank=True, default=datetime.date(2020, 3, 25)),
            preserve_default=False,
        ),
    ]
