# Generated by Django 2.2.13 on 2020-09-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20200325_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='supports_quick_entry',
            field=models.BooleanField(default=True),
        ),
    ]
