# Generated by Django 2.2.13 on 2020-09-26 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_account_supports_quick_entry'),
        ('services', '0016_service_supports_quick_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Tax'),
        ),
    ]
