# Generated by Django 2.1 on 2020-01-13 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20190923_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomponent',
            name='tax',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounting.Tax'),
        ),
    ]
