# Generated by Django 2.1 on 2020-01-13 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20200113_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysettings',
            name='default_warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.WareHouse'),
        ),
    ]
