# Generated by Django 2.1 on 2020-01-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_warehouseitem_last_check_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycontroller',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
