# Generated by Django 2.1 on 2020-03-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20200302_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycontroller',
            name='can_validate_orders',
            field=models.BooleanField(default=False),
        ),
    ]
