# Generated by Django 2.2.10 on 2020-09-05 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_auto_20200905_2123'),
        ('inventory', '0021_inventorycontroller_can_validate_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='billing_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Currency'),
        ),
    ]
