# Generated by Django 2.2.13 on 2020-09-12 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_remove_accountingsettings_default_accounting_period'),
        ('inventory', '0022_supplier_billing_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying', models.BooleanField(default=False)),
                ('selling', models.BooleanField(default=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Currency')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.InventoryItem')),
            ],
        ),
    ]
