# Generated by Django 2.2.13 on 2020-09-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_itemprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='supports_quick_entry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_company',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supports_quick_entry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='supports_quick_entry',
            field=models.BooleanField(default=True),
        ),
    ]
