# Generated by Django 2.1 on 2019-12-24 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_auto_20191224_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.Invoice')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.POSSession')),
            ],
        ),
    ]
