# Generated by Django 2.1 on 2020-02-07 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0011_auto_20200125_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrepresentative',
            name='employee',
            field=models.OneToOneField(limit_choices_to=models.Q(
                active=True), null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
    ]
