# Generated by Django 2.1 on 2020-02-08 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20190927_0513'),
        ('employees', '0024_payrollofficer_active'),
        ('common_data', '0014_auto_20200204_1148'),
        ('invoicing', '0012_auto_20200207_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('individual_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                        parent_link=True, primary_key=True, serialize=False, to='common_data.Individual')),
            ],
            options={
                'abstract': False,
            },
            bases=('common_data.individual',),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('contact', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='InteractionType',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('projected_closing', models.DateField(blank=True, null=True)),
                ('opportunity', models.FloatField(default=0.0)),
                ('probability_of_sale', models.FloatField(default=100.0)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('quotation', ' Quotation'), (
                    'invoice', 'Invoice'), ('sale', 'Sale'), ('cold', 'Cold')], default='lead', max_length=16)),
                ('contacts', models.ManyToManyField(to='invoicing.Contact')),
                ('organization', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='common_data.Organization')),
                ('owner', models.ForeignKey(
                    default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='invoicing.SalesRepresentative')),
            ],
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalesTeam',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('members', models.ManyToManyField(
                    to='invoicing.SalesRepresentative')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('progress', 'In Progress'), (
                    'cancelled', 'Cancelled'), ('completed', 'Completed')], default='planned', max_length=16)),
                ('created', models.DateTimeField(auto_now=True)),
                ('due', models.DateField()),
                ('event', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.Event')),
                ('lead', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='invoicing.Lead')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='invoicing.LeadSource'),
        ),
        migrations.AddField(
            model_name='lead',
            name='team',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.SalesTeam'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='lead',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.Lead'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='notes',
            field=models.ManyToManyField(to='invoicing.Note'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='sales_representative',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.SalesRepresentative'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='type',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='invoicing.InteractionType'),
        ),
    ]
