# Generated by Django 2.1 on 2020-02-08 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0013_auto_20200208_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesteam',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='leader', to='invoicing.SalesRepresentative'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.SalesRepresentative'),
        ),
    ]
