# Generated by Django 2.1 on 2020-03-02 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0018_auto_20200227_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='author',
        ),
        migrations.AlterField(
            model_name='interaction',
            name='notes',
            field=models.ManyToManyField(to='common_data.Note'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_validated_by',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Employee'),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
