# Generated by Django 2.2.10 on 2020-03-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0021_auto_20200315_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('quotation', 'Quotation'), ('won', 'Won'), ('lost', 'Lost')], default='lead', max_length=16),
        ),
    ]
