# Generated by Django 2.2.10 on 2020-03-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0015_auto_20200302_0714'),
        ('invoicing', '0022_auto_20200319_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='notes',
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.ManyToManyField(to='common_data.Note'),
        ),
    ]
