# Generated by Django 2.2.13 on 2020-09-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0029_customer_supports_quick_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
