# Generated by Django 2.2.10 on 2020-03-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0024_auto_20190910_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_email_age',
            field=models.PositiveSmallIntegerField(choices=[(7, 'One Week'), (30, 'One Month'), (90, 'Three Months')], default=30),
        ),
    ]
