# Generated by Django 2.2.10 on 2020-03-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftscheduleline',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='shiftscheduleline',
            name='shift',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.DeleteModel(
            name='ShiftSchedule',
        ),
        migrations.DeleteModel(
            name='ShiftScheduleLine',
        ),
    ]
