# Generated by Django 2.1 on 2020-01-25 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_auto_20191126_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingsettings',
            name='default_bookkeeper',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(active=True), null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Bookkeeper'),
        ),
        migrations.AlterField(
            model_name='adjustment',
            name='created_by',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(active=True), null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Bookkeeper'),
        ),
    ]
