# Generated by Django 2.1 on 2020-02-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_auto_20200125_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingsettings',
            name='start_of_financial_year',
        ),
    ]
