# Generated by Django 2.1 on 2020-02-07 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_remove_accountingsettings_start_of_financial_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookkeeper',
            name='employee',
            field=models.OneToOneField(default=1, limit_choices_to=models.Q(
                user__isnull=False), null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Employee'),
        ),
    ]
