# Generated by Django 2.1 on 2020-03-02 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_auto_20200220_1326'),
        ('accounting', '0018_auto_20200227_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='created_by',
        ),
        migrations.AddField(
            model_name='asset',
            name='initialized_by',
            field=models.ForeignKey(
                default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Employee'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='recorded_by',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='recorded_by',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='recorded_by',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='employees.Employee'),
        ),
    ]
