# Generated by Django 2.1 on 2020-03-02 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_auto_20200302_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='initialized_by',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(active=True), null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='recorded_by',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(active=True), on_delete=django.db.models.deletion.SET_DEFAULT, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='recorded_by',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(active=True), on_delete=django.db.models.deletion.SET_DEFAULT, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='recorded_by',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(active=True), on_delete=django.db.models.deletion.SET_DEFAULT, to='employees.Employee'),
        ),
    ]
