# Generated by Django 2.2.10 on 2020-08-02 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_auto_20200302_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_value_account', to='accounting.Account')),
                ('accumulated_depreciation_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overall_depreciation_account', to='accounting.Account')),
            ],
        )
    ]
