# Generated by Django 2.2.10 on 2020-08-02 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_auto_20200802_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.AssetCategory'),
        ),
    ]
