# Generated by Django 2.2.13 on 2020-09-12 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_auto_20200905_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingsettings',
            name='default_accounting_period',
        ),
    ]
