# Generated by Django 2.2.13 on 2020-09-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_auto_20200920_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='supports_quick_entry',
            field=models.BooleanField(default=True),
        ),
    ]
